// src/routes/projects/oblique-strategies/+page.svelte
<h1>Oblique Strategies</h1>

<div class="card bg-light">
  <div class="card-body">
    <p>
      <strong>Oblique Strategies</strong> é um método baseado em cartão para promover a criatividade criado em conjunto pelo músico / artista <em>Brian Eno</em> e o artista multimídia <em>Peter Schmidt</em>, publicado pela primeira vez em 1975.
    </p>
    <p>
      <a href="https://play.google.com/store/apps/details?id=com.github.mdssjc.oblique_strategies" target="_blank" rel="noreferrer">Instale o aplicativo para o <em>Android</em>!</a>
    </p>
    <p>
      Atualizado em 04/02/2013.
    </p>
  </div>
</div>

// angular-version/src/app/projects/oblique-strategies/oblique-strategies.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-oblique-strategies',
  templateUrl: './oblique-strategies.component.html',
  styleUrls: ['./oblique-strategies.component.sass']
})
export class ObliqueStrategiesComponent {

}

<div class="p-4">
  <h1>Oblique Strategies</h1>

  <div class="card">
    <p>
      <strong>Oblique Strategies</strong> é um método baseado em cartão para promover a criatividade criado em conjunto
      pelo músico / artista <em>Brian Eno</em> e o artista multimídia <em>Peter Schmidt</em>, publicado pela primeira
      vez
      em 1975.
    </p>
    <p>
      <a href="https://play.google.com/store/apps/details?id=com.github.mdssjc.oblique_strategies" target="_blank"
         rel="noreferrer">Instale o aplicativo para o <em>Android</em>!</a>
    </p>
    <p>
      Atualizado em 04/02/2023.
    </p>
  </div>
</div>
